services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: comqtt
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./plugin/auth/mysql/testdata/init.sql:/docker-entrypoint-initdb.d/init.sql